import { describe, expect, it } from "vitest";

import { resolveGameAsset } from "../game-assets/index.ts";

describe("game assets", () => {
  it.each([
    ["gameplay.bomb.sprite", "bomb.png"],
    ["gameplay.bomb.sprite.ruins", "bomb-ruins.png"],
    ["gameplay.bomb.flame", "flame.png"],
    ["gameplay.bomb.flame.ruins", "flame-ruins.png"],
    ["audio.bomb.place", "bomb_place.mp3"],
    ["audio.bomb.explode.default", "bomb_explode_default.mp3"],
    ["audio.bomb.explode.main", "bomb_explode_main.mp3"],
    ["audio.bomb.flames", "flames.mp3"],
    ["arena.theme.arcane-citadel.floor.base", "arenas/themes/arcane-citadel/floor-base.png"],
    ["arena.theme.arcane-citadel.floor.lane", "arenas/themes/arcane-citadel/floor-lane.png"],
    ["arena.theme.arcane-citadel.floor.spawn", "arenas/themes/arcane-citadel/floor-spawn.png"],
    ["arena.theme.arcane-citadel.wall", "arenas/themes/arcane-citadel/wall.png"],
    ["arena.theme.arcane-citadel.crate", "arenas/themes/arcane-citadel/crate.png"],
    ["arena.theme.verdant-ruins.floor.base", "arenas/themes/verdant-ruins/floor-base.png"],
    ["arena.theme.verdant-ruins.floor.lane", "arenas/themes/verdant-ruins/floor-lane.png"],
    ["arena.theme.verdant-ruins.floor.spawn", "arenas/themes/verdant-ruins/floor-spawn.png"],
    ["arena.theme.verdant-ruins.wall", "arenas/themes/verdant-ruins/wall.png"],
    ["arena.theme.verdant-ruins.crate", "arenas/themes/verdant-ruins/crate.png"],
    ["arena.theme.skyfoundry-bastion.floor.base", "arenas/themes/skyfoundry-bastion/floor-base.png"],
    ["arena.theme.skyfoundry-bastion.floor.lane", "arenas/themes/skyfoundry-bastion/floor-lane.png"],
    ["arena.theme.skyfoundry-bastion.floor.spawn", "arenas/themes/skyfoundry-bastion/floor-spawn.png"],
    ["arena.theme.skyfoundry-bastion.wall", "arenas/themes/skyfoundry-bastion/wall.png"],
    ["arena.theme.skyfoundry-bastion.crate", "arenas/themes/skyfoundry-bastion/crate.png"],
    ["arena.theme.tidal-foundry.floor.base", "arenas/themes/tidal-foundry/floor-base.png"],
    ["arena.theme.tidal-foundry.floor.lane", "arenas/themes/tidal-foundry/floor-lane.png"],
    ["arena.theme.tidal-foundry.floor.spawn", "arenas/themes/tidal-foundry/floor-spawn.png"],
    ["arena.theme.tidal-foundry.wall", "arenas/themes/tidal-foundry/wall.png"],
    ["arena.theme.tidal-foundry.crate", "arenas/themes/tidal-foundry/crate-mare-de-bronze.png"],
    ["arena.theme.ember-kiln.floor.base", "arenas/themes/ember-kiln/floor-base.png"],
    ["arena.theme.ember-kiln.floor.lane", "arenas/themes/ember-kiln/floor-lane.png"],
    ["arena.theme.ember-kiln.floor.spawn", "arenas/themes/ember-kiln/floor-spawn.png"],
    ["arena.theme.ember-kiln.wall", "arenas/themes/ember-kiln/wall.png"],
    ["arena.theme.ember-kiln.crate", "arenas/themes/ember-kiln/crate.png"],
    ["arena.shared.floor.base", "arenas/shared/floor-base.png"],
    ["arena.shared.floor.lane", "arenas/shared/floor-alt.png"],
    ["arena.shared.floor.spawn", "arenas/shared/floor-spawn.png"],
    ["arena.shared.wall", "arenas/shared/wall.png"],
    ["gameplay.crate.sprite", "gameplay/crates/sprites/crate.png"],
    ["gameplay.crate.break.0", "gameplay/crates/break/crate-break-0.png"],
    ["gameplay.crate.break.1", "gameplay/crates/break/crate-break-1.png"],
    ["gameplay.crate.break.2", "gameplay/crates/break/crate-break-2.png"],
    ["gameplay.crate.break.3", "gameplay/crates/break/crate-break-3.png"],
    ["gameplay.power-up.bomb.icon", "gameplay/power-ups/icons/power-bomb.png"],
    ["gameplay.power-up.flame.icon", "gameplay/power-ups/icons/power-flame.png"],
    ["gameplay.power-up.speed.icon", "gameplay/power-ups/icons/power-speed-rastro-relampago.png"],
    ["gameplay.power-up.speed.icon.simple", "gameplay/power-ups/icons/power-speed.png"],
    ["gameplay.power-up.remote.icon", "gameplay/power-ups/icons/power-remote.png"],
    ["gameplay.power-up.shield.icon", "gameplay/power-ups/icons/power-shield.png"],
    ["gameplay.power-up.bomb-pass.icon", "gameplay/power-ups/icons/power-bomb-pass.png"],
    ["gameplay.power-up.kick.icon", "gameplay/power-ups/icons/power-kick.png"],
    ["gameplay.power-up.short-fuse.icon", "gameplay/power-ups/icons/power-short-fuse-v2.png"],
    ["audio.match.start", "audio/match/match_start.mp3"],
    ["audio.match.win", "audio/match/match_win.mp3"],
    ["audio.match.round-end", "audio/match/round_end.wav"],
    ["audio.match.sudden-death-alarm", "audio/match/sudden_death_alarm.wav"],
    ["audio.power-up.collect.default", "audio/power-ups/powerup_collect.mp3"],
    ["audio.power-up.collect.bright", "audio/power-ups/powerup_collect_bright.mp3"],
    ["audio.power-up.collect.crystal", "audio/power-ups/powerup_collect_crystal.mp3"],
    ["audio.gameplay.shield-block-deflect", "audio/gameplay/shield_block_deflect.mp3"],
    ["effect.movement.speed-spark-trail", "effects/movement/speed-spark-trail.png"],
    ["ui.arena.victory-emblem", "ui/arena/arena-victory-emblem.webp"],
    ["ui.arena.stalemate-emblem", "ui/arena/arena-stalemate-emblem.png"],
    ["ui.launcher.match-bay", "ui/launcher/launcher-match-bay-v1.webp"],
    ["marketing.hero.arena-sigil", "marketing/hero-arena-sigil.webp"],
    ["marketing.hero.match-control", "marketing/hero-match-control-v2.webp"],
  ] as const)("resolves %s through the root module", (assetId, expectedFileName) => {
    const resolvedUrl = resolveGameAsset(assetId);

    expect(resolvedUrl.split("?")[0]?.replaceAll("\\\\", "/")).toMatch(new RegExp(`/${expectedFileName}$`));
  });
});
