export { createGameMechanics, MAX_ADVANCE_MS } from "./game-mechanics.ts";
export type { CreateGameMechanicsOptions } from "./game-mechanics.ts";
export {
  createDefaultMechanicsProgram,
  createMechanicsProgramFromModules,
  getDefaultMechanicsProgram,
  createMechanicsProgram,
  createDefaultModules,
} from "./composition.ts";
export {
  cloneMatchConfig,
  createFourSeatMatchConfig,
  createLocalDuel1v1MatchConfig,
  createMatchConfig,
  DEFAULT_CONTENT_REVISION,
  DEFAULT_MECHANICS_REVISION,
  DEFAULT_ROUND_DURATION_MS,
  DEFAULT_SEED,
  DEFAULT_TARGET_ROUND_WINS,
  MAX_ROUND_DURATION_MS,
  MAX_SEATS,
  MAX_TARGET_ROUND_WINS,
  MIN_ROUND_DURATION_MS,
  MIN_SEATS,
  MIN_TARGET_ROUND_WINS,
  roundSeedFor,
} from "./match-config.ts";
export {
  TICK_DURATION_MS,
  type MechanicsProgram,
  type StepResult,
} from "./kernel/program.ts";
export {
  ROUND_END_MS,
  ROUND_START_MS,
  SPAWN_PROTECTION_MS,
  RANNI_ICE_BLINK_SKILL_ID,
  ZED_LIVING_SHADOW_SKILL_ID,
  TICK_DURATION_MS as CONTRACT_TICK_DURATION_MS,
} from "./contracts.ts";
export {
  compileMechanics,
  MECHANICS_REVISION,
  MechanicsCompileError,
  PHASE_ORDER,
  SLICE_IDS,
  type CompiledMechanics,
  type ModuleCodecs,
  type ModuleSpec,
  type SystemSpec,
  type SystemRunContext,
  type PhaseId,
  type SliceId,
} from "./kernel/protocol.ts";
export {
  type CommandEnvelope,
  type CommandRejection,
  type KernelCommand,
  type StepInput,
  type ResolvedCommand,
} from "./kernel/commands.ts";
export {
  type WorldState,
  type WorldSlices,
  type FlameCause,
  type IntentEntry,
  type LocomotionEntry,
  type RosterEntry,
  type VitalsEntry,
  type BombEntry,
  type FlameEntry,
  type WorldPosition as KernelWorldPosition,
  type Velocity as KernelVelocity,
  WORLD_FORMAT_VERSION,
  UNITS_PER_TILE,
  BODY_HALF_EXTENT,
  BASE_SPEED_UNITS_PER_TICK,
  LANE_ASSIST_MAX_OFFSET,
  LANE_LONGITUDINAL_LOCK,
  LANE_CORRECTION_MAX,
  createArenaTiles,
  effectiveSolidKeySet,
  effectiveSolidTiles,
  freezeTile,
  freezePosition,
  freezeVelocity,
  tileOf,
  tileCenter,
  bodiesOverlap,
  bodyOverlapsTile,
  bodyWithinBounds,
  type PressureSlice,
  type PressureClosing,
  type PickupsSlice,
  type ProgressionSlice,
  type PickupItem,
  type ProgressionEntry,
} from "./kernel/world-state.ts";
export {
  arenaModule,
  competitorsModule,
  intentModule,
  locomotionModule,
  matchModule,
  ordnanceModule,
  powerupsModule,
  pressureModule,
  skillsModule,
} from "./modules/index.ts";
export {
  PRESSURE_FALL_MS,
  PRESSURE_INTERVAL_MS,
  PROGRESSION_BASE_FLAME_RANGE,
  PROGRESSION_BASE_MAX_BOMBS,
  PROGRESSION_MAX_CAP,
  buildPressurePath,
  derivePressureClosing,
  derivePressureProgress,
  hashUint32,
  bodyTileOverlapArea,
  impactAt,
  warningAt,
} from "./kernel/world-state.ts";
export {
  deriveRoundDropPlan,
  type DropPlanEntry,
  type RoundDropPlan,
} from "./modules/powerups/index.ts";
export {
  resolveMovementBatch,
  type MovementCandidate,
} from "./modules/locomotion/index.ts";
export {
  GAME_MECHANICS_VERSION,
  type BombSnapshot,
  type CompetitorId,
  type CompetitorSnapshot,
  type Direction,
  type FacadeCommandRejection,
  type FlameSnapshot,
  type GameCommand,
  type GameEvent,
  type GameMechanics,
  type GamePhase,
  type GameSnapshot,
  type LocalDuel1v1Options,
  type MatchConfig,
  type MatchConfigInput,
  type MatchPhase,
  type PowerUpSnapshot,
  type PowerUpType,
  type RoundOutcome,
  type ScoreEntry,
  type SeatAssignment,
  type SeatId,
  type SkillId,
  type SkillSnapshot,
  type TileCoord,
  type WorldPosition,
  type Velocity,
  type EliminationCause,
} from "./contracts.ts";
